/**
 * I campi del costruttore di stili.
 *
 * Ogni voce ha una spiegazione e un elenco di proposte da cliccare: quelle a
 * scelta multipla si sommano, le altre si sostituiscono, e in ogni caso si può
 * scrivere di proprio nel campo. `block` decide in quale dei tre blocchi dello
 * schema MiniMax finisce (metadati globali, voce, arrangiamento).
 */

export const FIELDS = [
  {block:"Global metadata", id:"genere", label:"Genere", multi:false,
   desc:"Il punto di partenza. Puoi anche incrociarne due (\"trip hop with bossa nova guitars\").",
   opts:["neapolitan neomelodic pop","modern italian pop","indie pop","alternative rock","hard rock",
         "punk rock","heavy metal","metalcore","lo-fi hip hop","boom bap hip hop","trap","melodic trap",
         "uk drill","drill","grime","contemporary R&B","neo-soul","funk","disco","nu disco","deep house",
         "future house","french house","techno","synthwave","italo disco","drum and bass","neurofunk",
         "ambient","cinematic orchestral","symphonic metal","opera","jazz trio","bossa nova","latin pop",
         "reggaeton","afrobeats","country ballad","indie folk","bluegrass","gospel","delta blues",
         "acoustic singer-songwriter","chanson francaise","tango","flamenco","K-pop","japanese city pop",
         "shoegaze","post-rock","dream pop","chamber pop","chillwave","hyperpop","phonk","trance"]},
  {block:"Global metadata", id:"bpm", label:"BPM", multi:false,
   desc:"Battiti al minuto. 60-80 ballata, 90-110 pop, 120-130 dance, 140+ energia alta.",
   opts:["62","72","82","92","100","104","110","120","128","140","150","174"]},
  {block:"Global metadata", id:"tonalita", label:"Tonalità", multi:false,
   desc:"Maggiore = luminoso, minore = malinconico. I modi (dorian, phrygian) danno un colore particolare.",
   opts:["C major","G major","D major","A major","F major","Bb major","A minor","E minor","B minor",
         "F# minor","C minor","D minor","G minor","D dorian","E phrygian","A mixolydian"]},
  {block:"Global metadata", id:"mood", label:"Mood e arco emotivo", multi:true,
   desc:"Dove parte e dove arriva il brano. La progressione conta più dell'aggettivo singolo.",
   opts:["warm and nostalgic turning hopeful","urgent and defiant","calm and slightly melancholic",
         "tense building to euphoric release","tender and reflective","dark and brooding","playful and cheeky",
         "triumphant and cinematic","dreamy and hazy","bittersweet","sensual and slow-burning",
         "furious","eerie and unsettling","carefree summer joy","grief turning into acceptance"]},
  {block:"Global metadata", id:"contesto", label:"Dove si ascolta", multi:false,
   desc:"La scena mentale: aiuta il modello a scegliere densità, dinamica e spazio.",
   opts:["late-summer evening drive","festival main stage","late-night study session",
         "title sequence of a sci-fi film","empty church at dawn","rainy window","beach at sunrise",
         "boxing gym","wedding first dance","smoky dive bar","packed arena","forest at dawn",
         "video game boss fight","morning commute","after-hours club"]},
  {block:"Global metadata", id:"produzione", label:"Tipo di produzione", multi:true,
   desc:"Come suona il disco, non cosa suona: pulizia, colore, epoca.",
   opts:["polished radio production with wide stereo image","raw live-room recording",
         "analog tape saturation","lo-fi and dusty with vinyl noise","modern loud mix with deep sub",
         "intimate close-miked with minimal processing","80s gated reverb","cinematic wide dynamics",
         "bedroom demo feel","hi-fi audiophile clarity","heavily compressed and aggressive"]},

  {block:"Voce", id:"voce", label:"Chi canta", multi:false,
   desc:"Scegli \"no vocals\" per un brano interamente strumentale.",
   opts:["female lead","male lead","androgynous vocal","duet, female and male leads",
         "full choir","child-like voice","no vocals"]},
  {block:"Voce", id:"timbro", label:"Timbro", multi:true,
   desc:"Il colore della voce.",
   opts:["warm mid-range timbre","breathy alto","bright soprano","raspy and forward","deep baritone",
         "smooth tenor","husky and smoky","nasal and youthful","whispery","powerful belting",
         "heavily autotuned neomelodic voice"]},
  {block:"Voce", id:"interpretazione", label:"Interpretazione", multi:true,
   desc:"Come viene cantata: dinamica fra strofa e ritornello, fraseggio, attacco.",
   opts:["intimate in the verses and full-voiced in the chorus","conversational phrasing",
         "shouted in the chorus","behind the beat and relaxed","rapid rap flow",
         "operatic sustained notes","staccato and rhythmic","emotional cracks and vibrato","spoken word"]},
  {block:"Voce", id:"armonie", label:"Cori e armonie", multi:true,
   desc:"Cosa succede intorno alla voce principale.",
   opts:["stacked octave harmonies on the hook","close three-part harmonies","gospel choir stacks",
         "a single close harmony","call and response backing vocals","wordless oohs","no backing vocals"]},
  {block:"Voce", id:"effetti", label:"Effetti sulla voce", multi:true,
   desc:"Il trattamento: quanto è vicina o lontana, quanto è lavorata.",
   opts:["light plate reverb and slap delay","long reverb tail","tape delay","tuned and glossy",
         "vocoder doubling","telephone filter in the intro","doubled and hard-panned","dry and upfront"]},

  {block:"Arrangiamento", id:"primari", label:"Strumenti principali", multi:true,
   desc:"Uno o due: sono quelli che senti sempre, la firma del brano.",
   opts:["electric piano","grand piano","Rhodes chords","Hammond organ","clean electric guitar",
         "distorted rhythm guitars","fingerpicked acoustic guitar","nylon-string guitar","slide guitar",
         "analog synth arpeggios","warm synth pads","string section","brass section","saxophone",
         "muted trumpet","mandolin","accordion","harp","church organ","marimba","808 bass"]},
  {block:"Arrangiamento", id:"secondari", label:"Strumenti secondari", multi:true,
   desc:"Colore di contorno: entrano ed escono, riempiono i vuoti.",
   opts:["analog synth pads","muted trumpet stabs","staccato strings","low brass","flute",
         "solo cello","bells and chimes","steel drums","sitar","koto","music box","whistling","claps"]},
  {block:"Arrangiamento", id:"groove", label:"Groove", multi:false,
   desc:"Come si muove il tempo: la sensazione fisica del ritmo.",
   opts:["laid-back groove","driving eighth-note groove","swung groove","four-on-the-floor",
         "half-time shuffle","syncopated latin groove","motorik krautrock pulse","free-time rubato","breakbeat"]},
  {block:"Arrangiamento", id:"basso", label:"Basso", multi:false,
   desc:"Regge tutto: il fondo del brano.",
   opts:["round sub-bass","fat upright bass","picked overdriven bass","slap bass","808 glides",
         "walking bass line","minimal root notes","melodic counterline bass"]},
  {block:"Arrangiamento", id:"percussioni", label:"Percussioni", multi:true,
   desc:"Batteria e affini, compreso quando entrano.",
   opts:["brushed acoustic drums","hard-hitting live drums","tight programmed drum machine",
         "dusty lo-fi drums","trap hi-hat rolls","handclaps and finger snaps","congas and shakers",
         "taiko hits","tambourine","no drums until the chorus"]},
  {block:"Arrangiamento", id:"texture", label:"Texture e atmosfere", multi:true,
   desc:"Tutto quello che non è una nota: rumori, ambienti, code.",
   opts:["airy background textures","vinyl crackle","rain and city ambience","tape hiss",
         "granular pads","choir swells","crowd field recording","whispered layers","white-noise risers","sub drops"]},
  {block:"Arrangiamento", id:"spazio", label:"Spazializzazione", multi:false,
   desc:"Quanto è largo il quadro stereo e quanto è grande la stanza.",
   opts:["wide immersive stereo","narrow and warm, almost mono","dry and close",
         "cathedral-sized reverb","panned call and response","headphone-friendly depth"]}
];
